name = "Modia"
uuid = "cb905087-75eb-5f27-8515-1ce0ec8e839e"
authors = ["Hilding Elmqvist <Hilding.Elmqvist@Mogram.net>", "Martin Otter <Martin.Otter@dlr.de>"]
version = "0.4.1-dev"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
ModiaLang = "34b37210-eaa3-4b48-8781-0b87bf559981"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DifferentialEquations = "6.16"
ModiaLang = "0.7.2"
Reexport = "1.0, 0.2"
Unitful = "1.6, 1.5, 1.4, 1.3"
julia = "1.6, 1.5"
