name = "TinyModia"
uuid = "0169e107-af13-440d-89df-ca21e82123ce"
authors = ["Hilding Elmqvist <Hilding.Elmqvist@Mogram.net>", "Martin Otter <Martin.Otter@dlr.de>"]
version = "0.7.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
ModiaBase = "ec7bf1ca-419d-4510-bbab-199861c55244"
ModiaPlot = "951137b1-a5aa-4c03-8412-295bfee9a204"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DataFrames = "0.22, 0.21, 0.20, 0.19"
DataStructures = "0.18, 0.17"
DifferentialEquations = "6.16"
Measurements = "2.5, 2.4, 2.3"
ModiaBase = "0.7.2"
ModiaPlot = "0.7.1"
MonteCarloMeasurements = "0.10"
Reexport = "1.0.0"
Unitful = "1.6, 1.5, 1.4, 1.3"
julia = "1.6, 1.5"
